defmodule HTTPlaster.Adapters.UnimplementedError do
  @moduledoc """
  Exception that is raised when no default adapter is specified
  """

  @type t :: %__MODULE__{}

  defexception message: """
  No adapter specified.

  You have not specified an adapter for HTTPlaster to use. By default,
  HTTPlaster will route requests through the Unimplemented adapter which
  will always return an error.

  In order to use HTTPlaster, you will need to specify an adapter in your
  application's configuration. Adapters can be found on Hex, by searching
  for "httplaster": https://hex.pm/packages?search=httplaster. The hackney
  adapter (`httplaster_adapters_hackney`) is recommended.
  
  Once installed as a depencdency, specify the adapter as the default inside
  the `config/config.exs` file generated by Mix. For example, to specify
  the Hackney adapter:

      config :httplaster, adapter: HTTPlaster.Adapters.Hackney

  Individual adapters may have further configuration instructions that
  are specific to their implementations. You should read through the
  documentation for your chosen adapter.
  """
  
  @spec exception(nil) :: t
  def exception(_), do: %__MODULE__{}
end
